### ISSUE TITLE
sleepPinInterrupt

### ISSUE THREAD

**Issue by cemkaan** [n0m1/Sleep_n0m1#17]
error: 'class Sleep' has no member named 'sleepPinInterrupt'
sleep.sleepPinInterrupt(alarmPin,LOW); //(interrupt Pin Number, interrupt State)

https://create.arduino.cc/editor/cemkaan/ce3fcfa7-0e2f-449c-b01a-c9c9eadb30c8/preview

**Comment by nullboundary** [comment]
Its there. Maybe you are using an old version of the library? This question is quite old now so I will close it. Hopefully you solved it.
