### ISSUE TITLE
Arduino ATMEGA2560 sleep not working properly

### ISSUE THREAD

**Issue by FreedomLabsIO** [n0m1/Sleep_n0m1#9]
I've made this small code to test "Sleep_n0m1" in the MEGA2560:

```
#include <Sleep_n0m1.h>

Sleep sleep;

void setup() {

}

void loop() {

  delay(3000);

  sleep.pwrDownMode(); // 9 mA
  sleep.sleepDelay(10000);

}
```

The problem is that it's working only in the second call to the "sleepDelay" function.

In my code, the board starts drawing ~80 mA, and after 3 secs goes into the first "pwrDownMode" drawing ~60 mA. After 10 secs it wakes up drawing ~80 mA again and after 3 secs goes into the second "pwrDownMode" but now consuming only ~28 mA !!

**Comment by nullboundary** [comment]
Hi Bruno,

Actually that sounds correct for how the library is currently implemented. 

The way it works is in the first cycle of sleepDelay() the chip is only going into an idle sleep mode and is calibrating the watch dog timer. After the first cycle then the device will go into proper power down sleep mode. Periodically it will go back into calibration mode to make sure the watch dog is keeping time correctly. (the watchdog timer drifts off time quickly). You can also adjust the calibration interval (defaults to 100 sleep/wake cycles).  setCalibrationInterval()

Issue #5 has a suggestion for a fix that would reduce the amount of time spent in idle sleep mode. I think its a good idea, I just haven't had time to implement it. Actually the coding part is simple, I just would want to test it throughly to make sure a shorter calibration time doesn't throw off the sleep time in anyway. 

I always welcome pull requests if you think you can fix this.
